import { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/navbar";
import { Toast } from "flowbite-react";
import ToasterProvider from "@/providers/ToasterProvider";


export const metadata: Metadata = {
  title: "Bidify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToasterProvider/>
        <Navbar />
        <main className="container mx-auto px-5 pt-10">{children}</main>
      </body>
    </html>
  );
}
